### ISSUE TITLE
Add link back to relevant commits from uploaded diffs page

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#102]
If you are looking at the uploaded diffs, you are left without the context of the commits that caused those diffs. It would be nice to be able to include a link when generating this page that gives people a way to get back.

**Comment by lencioni** [comment]
It might be nice to be able to include other descriptive information. For a GitHub setup, this could include things like the user that triggered the build, the name of the branch, and a link to the PR. For non-PR-based workflows, perhaps it could include the commit message.

**Comment by trotzig** [comment]
Closing, as the link-back approach was implemented in d35a5cc. @lencioni feel free to reopen if you feel it's important we add other bits of metadata (or open a new issue).
