### ISSUE TITLE
Add og tags for diff page

### ISSUE THREAD

**Issue by trotzig** [Galooshi/happo#105]
At Brigade, we often post links to happo diffs in Slack. If the document contained a few og tags, it would show up in a nicer way. 

Some ideas:
- use the first diff image as the og:image
- summarize the results in the og:description, e.g. "3 diffs, 2 new snapshots"

**Comment by lencioni** [comment]
I think this is a good idea. It is unlikely that I will work on this since our diffs have restricted access, so this won't work for us.

Another idea for the description: it would be nice to do this alongside #102 and include a reference to the commits.
