### ISSUE TITLE
Diffs page title has weird character in it

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#121]
I just updated to Happo 2.3.0 and my first diffs upload has a weird character in its title.

> 2 diffs Â· Happo

![screen shot 2016-08-29 at 8 29 22 am](https://cloud.githubusercontent.com/assets/195534/18056938/d61f333c-6dc2-11e6-88e0-14c4d6f51e1e.png)

This upload had 2 diffs and no new examples.

**Comment by trotzig** [comment]
I bet we need to explicitly set encoding somewhere. I can't find where though from the s3 docs (which are huuuuge).

**Comment by lencioni** [comment]
I have verified that this has been fixed in v2.4.0.
