### ISSUE TITLE
Add horizontal scrolling for diff view

### ISSUE THREAD

**Issue by trotzig** [Galooshi/happo#133]
For full-screen/wide snapshots, the diff view has to be horizontally scrolled in order to see everything. It would be better I think if the diff view was scrolled separately from the page so that headers and such stay in the same position.

**Comment by lencioni** [comment]
@trotzig did we do this? I seem to recall something that implemented this.

**Comment by trotzig** [comment]
Yep! Side-scrolling in combination with default zoom 1 on mobile made the experience even better. 

<img width="340" alt="screen shot 2016-10-02 at 20 58 51" src="https://cloud.githubusercontent.com/assets/578277/19022941/2aa89dcc-88e3-11e6-8a72-366368bab2b3.png">
