### ISSUE TITLE
Snapshots incorrectly cropped when subpixel positioning used

### ISSUE THREAD

**Issue by trotzig** [Galooshi/happo#151]
At Brigade, we have a few happo components that have a subpixel position from the top. This is unintentional, and I'm fixing that. Here's an example snapshot:

![-picture- fallbacktext small_extra_large_current](https://cloud.githubusercontent.com/assets/578277/18471947/7f409fa8-79b4-11e6-9391-9e13ea29eacf.png)

When I render that example in Firefox, I get this bounding rectangle:

```
> happo.getFullRect();
Object { bottom: 25.466659545898438, left: 0, right: 25, top: 0.4666595458984375, width: 25, height: 25 }
```

When we pass back the rectangle bounds to the Ruby code, we round the numbers:

```
> happo.processExample(happo.defined['<ProfilePicture> small']);
Object { description: "<ProfilePicture> small", width: 25, height: 25, top: 0, left: 0 }
```

Notice how the subpixel positioning is no longer represented. This means that the snapshot in the above example is cut off too soon.

**Comment by trotzig** [comment]
Our internal problem (causing the subpixel positioning) was that we have the `<body>` set to `display: inline-block`. By setting `vertical-align: top` we avoid subpixeling. Git history tells me we do this to fix modal scrolling on mobile (@janpaul123 do you remember? 😄).

**Comment by lencioni** [comment]
I think we need to round the values before calculating width/height.
