### ISSUE TITLE
Spurious diffs from elements with border-radius and a background image

### ISSUE THREAD

**Issue by trotzig** [Galooshi/happo#153]
We have this component in our code base:

![-ballotguidesharecard-_small_current](https://cloud.githubusercontent.com/assets/578277/18500163/5440d8a4-7a45-11e6-8500-92f75788cad7.png)

It often ends up having a diff in our happo run without having changed. Based on the diff it looks like there's some different anti-aliasing on the rounded borders at the top. See this diff:
http://s3.amazonaws.com/diffux_ci-diffs/d871861a-667a-45a3-8286-f8f801f94f93/index.html#PEJhbGxvdEd1aWRlU2hhcmVDYXJkPnNtYWxs

My suspicion is that Firefox has slightly different anti-aliasing behavior when rounding an element with a background image that is loaded from cache versus loaded the first time.

**Comment by lencioni** [comment]
Is this a recent development or has it been happening for a while?

**Comment by trotzig** [comment]
This is a fairly new component, so I can't say for sure. Though I have a
vague memory of seeing this in the past too. So probably not new.

**Comment by lencioni** [comment]
What version of Firefox are you running? I've been using Travis, which defaults to 31.0esr. I was seeing a number of strange spurious diffs, then I recently updated Travis to use 47.0.1 and all of the spurious diffs seem to be resolved.

**Comment by trotzig** [comment]
If I'm reading our docker setup right, it's `firefox-45.1.0-1.el7.centos`. I'll talk to people to see if we can upgrade.

**Comment by trotzig** [comment]
Closing this issue. We have a workaround (using an inlined base64 image for the happo example).
