### ISSUE TITLE
Diff pages with hundreds of results can be very slow and unusable

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#155]
I recently saw a diff page that had 470 diffs and 318 new examples. As I scrolled near the bottom of the page, things became very slow and unusable. I'm actually surprised the tab didn't crash.

I think it was slow while it was rendering all of the diffs. It might be worth queueing them up so we can keep the page responsive.

For my own reference for later: 75e93591-60d6-4100-87fe-4299912c592a

**Comment by trotzig** [comment]
We could have a pool of workers for this I think.

**Comment by lencioni** [comment]
Yeah, I think that would be good. It probably also wouldn't be a bad idea to spend some time optimizing adiff, which we likely need to do anyway to fix #154.

**Comment by trotzig** [comment]
I don't think this should still be an issue with our recent improvements to performance.
