### ISSUE TITLE
New examples with plus signs end up with broken images

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#156]
Noticed in 2.8.0.

<img width="595" alt="screen shot 2016-09-22 at 3 11 27 pm" src="https://cloud.githubusercontent.com/assets/195534/18767945/e9bf0364-80d6-11e6-8564-7b97d3ed0e9c.png">

I think we messed up some encoding somewhere along the way.

**Comment by trotzig** [comment]
:sad_trombone:

**Comment by trotzig** [comment]
Fixed in https://github.com/Galooshi/happo/commit/f03b5be572d2fea85f1b644b27dd0a0df469caaf
