### ISSUE TITLE
[Bug] Options dropdown menu (•••) is too large

### ISSUE THREAD

**Issue by nebs** [Galooshi/happo#218]
There's only one option but the box looks like it's sized to show 2 options.

<img width="255" alt="screen shot 2017-11-09 at 4 08 40 pm" src="https://user-images.githubusercontent.com/2637098/32629799-6ac4dda4-c568-11e7-9abe-4aa3ef457d72.png">
<img width="272" alt="screen shot 2017-11-09 at 4 14 22 pm" src="https://user-images.githubusercontent.com/2637098/32630043-340bbaf2-c569-11e7-94d4-ea6a5e4f1831.png">

Noticed in this brigade link: https://happo.io/compare?q=ce2663c2717eb5304b141b4cbc618e76001872f9..c705436d56c14b2e24cc025b4b61044439ba981b&a=3#

**Comment by trotzig** [comment]
Thanks for finally getting that issue title right! 😉 

I was planning to add more to this menu, but it never happened. I wonder if it would be best to remove the overflow icon and use a different icon instead, taking action on click? I kind of want the "Mark as equal" action to be a few clicks out though, as it's not something you'd do very often.

**Comment by nebs** [comment]
I think keeping the overflow makes sense, even if it's just one option.  Besides providing a buffer it also makes it more clear because this is a non-standard action so using an icon might not be very clear (people will probably hover and wait for the tooltip anyway). 

The icon pattern could work if you show a confirmation toast when it's pressed and allow users to undo the action by pressing the icon again. That way the cost of not knowing what the icon does is minimal.

**Comment by trotzig** [comment]
I removed the min-height on the dropdown now. Thanks for the report @nebs!
