### ISSUE TITLE
happo-target-react-native repo?

### ISSUE THREAD

**Issue by mebowen** [Galooshi/happo#221]
Hello! I think to GitHub via the https://www.npmjs.com/package/happo-target-react-native page throws a 404, and I haven't been able to find the repo anywhere. Was that project deprecated for some reason?

**Comment by trotzig** [comment]
This package was removed in https://github.com/Galooshi/happo/pull/216, mostly because it was never finished and we wanted to ship version 5.

**Comment by mebowen** [comment]
@trotzig thanks for the info! That is a shame, though. Might be useful to add a "DEPRECATED" warning at the top of the NPM page for it.
