### ISSUE TITLE
Approving/rejecting a diff from the Review page appears to be broken

### ISSUE THREAD

**Issue by trotzig** [Galooshi/happo#71]
It's actually not broken, but when you reject/approve we re-render the page using information in the `result_summary.yaml` which is never updated.

**Comment by lencioni** [comment]
I'm not sure approve/reject buttons make sense for this project any more. What do you think about removing them?

**Comment by trotzig** [comment]
that sounds good.

**Comment by trotzig** [comment]
If we do, we can simplify how we store files. Instead of keeping a baseline and then generating a candidate we can simply store a "current" file and a "previous". If we encounter a current image while snapshotting, we rename it "previous" and run the diffs against that image.
