### ISSUE TITLE
Running `diffux run --help` runs my tests

### ISSUE THREAD

**Issue by jammons** [Galooshi/happo#72]
I was expecting it to output some kind of help method that would tell me how to target a specific test to run.

**Comment by trotzig** [comment]
Thanks for the report. We need a better way to handle command-line parsing. Right now it's too naive. Ideas are welcome!

**Comment by lencioni** [comment]
When we rewrite in JS, we can use the commander package for this, like we do in import-js.

**Comment by trotzig** [comment]
This will be better with the upcoming 3.0 release. There's no longer a default command, so running only `happo` will show you the help section.
