### ISSUE TITLE
Move to Galooshi

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#79]
I think we should:

- [x] mark [diffux](https://github.com/diffux/diffux) as deprecated
- [x] retire the [diffux core gem](https://github.com/diffux/diffux-core)
- [x] move the relevant diffux core code into this project
- [x] rename this project to "Happo"
- [x] move this project to the Galooshi organization

**Comment by lencioni** [comment]
I asked around for new names, here's a few of the better ones we came up with:

- diffooey (diffUI)
- pixelwatch
- odo (the shapeshifter, unfortunately taken on npm)
- gaius (as in [Gaius Baltar](https://en.wikipedia.org/wiki/Gaius_Baltar))

I am currently leaning toward gaius. What do you think?

**Comment by trotzig** [comment]
Maybe we should just call it Diffui? It can be pronounced diffooey. Or maybe that's what you suggested? I'm neutral on the Gaius idea, I'm not a mega fan of Battlestar Galactica. 

Alternatively (and half-seriously, half-jokingly), my nephew just came up with "Happo Carappo". He gave me a drawing on my birthday with a glued-on airplane and the text "Happo Carappo, here comes the Söderkvist people". He's three years old.

**Comment by lencioni** [comment]
How about just Happo? I like that!

**Comment by trotzig** [comment]
Happo sounds like a startup, so yeah!

**Comment by lencioni** [comment]
It fits in well with "Galooshi" too. :)

**Comment by lencioni** [comment]
If you still have the drawing, I'd love to see a picture of it here.

**Comment by trotzig** [comment]
Unfortunately not :(

**Comment by lencioni** [comment]
I added a deprecation notice to diffux core in https://github.com/diffux/diffux-core/commit/32febef8a6ea850074da4e9848d34681a01bc1b6
