### ISSUE TITLE
Need an updated demo GIF for the readme

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#90]
Since we've renamed the project and changed the command, we should update the demo GIF in the readme to match.

I don't currently have a project set up to use this, so could you take care of this when you have some time @trotzig? This is not urgent.

**Comment by trotzig** [comment]
Sure thing! I can't promise when it will happen but I'll try to get to it
soon. Probably when I make the switch for the brigade codebase.

**Comment by lencioni** [comment]
Fixed by 9fcb2fa56f0391bbfb2a3f66ef133fbf5e8331e2
