### ISSUE TITLE
Doesn't send 404s for files that are not found

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#95]
I believe that the change from #86 made it so that files that are not found will not result in 404 errors. I'm not a Sinatra expert, but I think we need to add something like

```rb
halt 404, "Not found"
```

if we can't find the file.

cc: @serena-w

**Comment by trotzig** [comment]
I'm guessing this doesn't really affect the general `happo` run in any significant way, right?

**Comment by lencioni** [comment]
That's right. The main impact it has is if you are running happo in debug mode and are using the new public directory setting and don't have things set up quite right so the files aren't there, instead of 404s you'll get 200s.

**Comment by lencioni** [comment]
This was fixed by #96.
